# Description
# -----------
# This workflow builds and releases the Docker image to Harbor, then deploys out to the kubernetes environment.
#
# Setup
# -----
# 1. Create the following secrets inside GitHub:
#    - LMS_GH_TOKEN (Personal access token for the lmsgit user that has read access to other repositories)
#    - LMS_MAVEN_SETTINGS (Base64 encoded settings.xml file)
#    - LMS_REGISTRY_PASSWORD (Registry password - push access)
#    - LMS_REGISTRY_USERNAME (Registry username)
# 2. Create the following environments, representative of the deployments:
#    - reg
#    - stg
#    - prd
# 3. Create the following secrets in each of the above environments
#    - LMS_KUBECONFIG_DEPLOYER (Base64 encoded kubernetes deployment service account for the appropriate cluster)
# 4. Create the following variables in each of the above environment
#    - DOCKER_TAG (tag name for the docker image that will be deployed i.e. stable, unstable-reg, etc)
# 5. Create the following variables in the repository
#    - IMAGE_REPO_NAME (Harbor registry name where the docker image will be pushed)
#    - DEPLOY_DIR (Directory where the helm deployment files can be found)
#    - JAR_FILE (Name of the application jar file)
#    - K8S_RELEASE_PREFIX (Kubernetes release name prefix for the deployed application)
#    - BUILD_PROFILES (Comma separated list of maven build profiles that need to be activated)

name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      server_env:
        type: environment
        required: true
        description: Select deployment env
        default: reg
      helm_deployer_branch:
        required: true
        description: Indicate the branch that contains the helm deployment files
        default: develop

jobs:
  mvn_build_deploy:
    uses: indiana-university/lms-githubaction-library/.github/workflows/kube-deploy.yml@v1
    with:
      java_version: 25
      server_env: ${{ github.event.inputs.server_env }}
      helm_deployer_branch: ${{ github.event.inputs.helm_deployer_branch }}
    secrets:
      LMS_MAVEN_SETTINGS: ${{ secrets.LMS_MAVEN_SETTINGS }}
      LMS_GH_TOKEN: ${{ secrets.LMS_GH_TOKEN }}
      LMS_REGISTRY_USERNAME: ${{ secrets.LMS_REGISTRY_USERNAME }}
      LMS_REGISTRY_PASSWORD: ${{ secrets.LMS_REGISTRY_PASSWORD }}
      LMS_KUBECONFIG_DEPLOYER: ${{ secrets.LMS_KUBECONFIG_DEPLOYER }}
