# Description
# -----------
# This workflow builds and releases the maven artifact
#
# Setup
# -----
# 1. Create the following secrets inside GitHub:
#    - LMS_GIT_CONFIG (Base64 encoded .gitconfig file)

name: Maven Release

on:
  workflow_dispatch:
jobs:
  release:
    uses: indiana-university/lms-githubaction-library/.github/workflows/release.yml@v1
    with:
      java_version: 25
    secrets:
      LMS_GIT_CONFIG: ${{ secrets.LMS_GIT_CONFIG }}
